### ISSUE TITLE
Orogen complains about missing std headers on ubuntu 18.04 fresh bootstrap

### ISSUE THREAD

**Issue by planthaber** [rock-core/base-orogen-std#7]
Can't say whether this comes from typelib or orogen, so i'm starting here:

```
/usr/bin/ruby2.5 -S /home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/tools/orogen/bin/orogen --corba --extensions=metadata_support --no-rtt-scripting --parallel-build=4 --transports=corba,mqueue,typelib --type-export-policy=used std.orogen
in directory /home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/base/orogen/std
/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/install/lib/ruby/2.5.0/typelib.rb:140: warning: constant ::Fixnum is deprecated
In file included from /tmp/orogen_gccxml_input20180613-5171-1sq57ps.hpp:1:
/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/install/include/orogen_metadata/Metadata.hpp:4:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/base/orogen/std/std.orogen:31: failed to preprocess /home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/install/include/orogen_metadata/Metadata.hpp "castxml --castxml-gccxml -E -I/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/base/orogen/std -I/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/base/orogen/std/.orogen/typekit/types -I/home/dfki.uni-bremen.de/planthaber/dfki/rock/rock_core/install/include -DOROCOS_TARGET=gnulinux -D__orogen2 /tmp/orogen_gccxml_input20180613-5171-1sq57ps.hpp /tmp/gcc-debug" (OroGen::ConfigError)
Exit: pid 5171 exit 1

```

**Comment by planthaber** [comment]
planthaber@SPLANTHABER-U:~/dfki/rock/rock_core$ cat .autoproj/config.yml 
---
ruby_executable: "/usr/bin/ruby2.5"
gems_install_path: "/home/dfki.uni-bremen.de/planthaber/.autoproj/gems"
prefer_indep_over_os_packages: false
osdeps_mode: all
reused_autoproj_installations: []
manifest_source:
  type: git
  url: http://github.com/rock-core/buildconf
GITHUB: http,ssh
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: 'git@github.com:'
GITHUB_PRIVATE_ROOT: 'git@github.com:'
operating_system:
- - ubuntu
  - debian
- - '18.04'
  - lts
  - bionic
  - beaver
  - default
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
cxx11: true
typelib_cxx_loader: castxml
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb

**Comment by planthaber** [comment]
This page led to the solution:
https://answers.unrealengine.com/questions/366547/building-on-linux-setupsh-fatal-error-vector-file.html

I had gcc-8 installed because of the "go" compiler i installed.

The minimal example:

```cpp
     #include <iostream>
      
      int main() {
          std::cout << "Hello, world!\n";
          return 0;
      }
```
Running castxml on that file, resulted in the same error, but gave the hint:

planthaber@SPLANTHABER-U:~/dfki/rock/rock_core/test$ castxml test.cpp -v
```
clang version 4.0.1-1build1 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: 
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8.0.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
Candidate multilib: .;@m64
Selected multilib: .;@m64
clang -cc1 version 4.0.1 based upon LLVM 4.0.1 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/backward"
ignoring nonexistent directory "/usr/include/clang/4.0.1/include/"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++
 /usr/local/include
 /usr/share/castxml/clang/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
test.cpp:2:15: fatal error: 'iostream' file not found
     #include <iostream>
              ^~~~~~~~~~
1 error generated.
```

After uninstalling gcc-8 it was ok.

I suppose libgcc-8-dev was not installed and so the headers were missing

**Comment by planthaber** [comment]
actually, it is the "g++-8" ubuntu package, that is missing.

**Comment by doudou** [comment]
> actually, it is the "g++-8" ubuntu package, that is missing.

Well ... does this mean that we must install g++-8 along with castxml on Ubuntu 18.04 ? If yes, we probably should be adding it in the castxml osdeps.

**Comment by planthaber** [comment]
> Well ... does this mean that we must install g++-8 along with castxml on Ubuntu 18.04 ?

No, default gcc in 18.04 is gcc-7, no castxml issue here.

This occurs only when the gcc-8 packages are installed and NOT g++-8.

Castxml has some mechanism to determine the installed gcc versions and uses the include dir of the highest one. It finds gcc-8, it tries to use the gcc-8 cpp headers, but they are part of the g++-8 package, which is not installed.

Again: Default installations are not afected
